openapi: 3.0.1
info:
  title: User API
  version: 1.1.0

paths:
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: OK

  /orders:
    post:
      summary: Create order
      responses:
        "201":
          description: Created
